services:

  #
  # Media Content Services
  #

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - ${HTPC_CONFIG_DIR}/nginx:/data
      - ${HTPC_CONFIG_DIR}/certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Plex Media Server (https://plex.tv)
  plex-server:
    image: plexinc/pms-docker
    container_name: plex-server
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - PLEX_CLAIM=${HTPC_PLEX_CLAIM}
      - VERSION=docker
    volumes:
      - ${HTPC_CONFIG_DIR}/config:/config
      - ${HTPC_CONFIG_DIR}/transcode:/transcode
      - ${HTPC_DATA_DIR}:/data
    restart: always
    ports:
      - 1900:1900/udp
      - 3005:3005/tcp
      - 32400:32400/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469/tcp
      - 8324:8324/tcp
    labels:
      - com.centurylinklabs.watchtower.enable=true
    network_mode: host

  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - MAXMEM=2048
    volumes:
      - ${HTPC_CONFIG_DIR}/ubooquity:/config
      - ${HTPC_DATA_DIR}/Books:/books
      - ${HTPC_DATA_DIR}/Comics:/comics
      - ${HTPC_DATA_DIR}:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    network_mode: host

  #
  # Media Content Management Tools
  #

  # Plex Meta Manager ()
  #   Media metadata, collections, and playlists organizer
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      - ${HTPC_CONFIG_DIR}/plex-meta-manager:/config
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Unmanic ()
  #   Media optimizer
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
    volumes:
      - ${HTPC_CONFIG_DIR}/unmanic:/config
      - ${HTPC_DATA_DIR}:/library
      - ${HTPC_WORK_DIR}/unmanic:/tmp/unmanic
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Prowlarr (https://github.com/Prowlarr/Prowlarr)
  #   UseNet & Torrent indexer proxy and management
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Bazarr ()
  #   Subtitle Management
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/bazarr:/config
      - ${HTPC_DATA_DIR}/Movies:/movies #optional
      - ${HTPC_DATA_DIR}/TV:/tv #optional
    ports:
      - 6767:6767
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Lidarr ()
  #   Music Media Management
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/lidarr:/config
      - ${HTPC_DATA_DIR}/Music:/music #optional
      - ${HTPC_WORK_DIR}/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Maylar (https://github.com/mylar3/mylar3)
  #   Comic Book Media Management
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/mylar:/config
      - ${HTPC_DATA_DIR}/Comics:/comics
      - ${HTPC_WORK_DIR}/downloads:/downloads
    ports:
      - 8090:8090
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Sonarr (https://sonarr.tv)
  #   Tv Show Media Management
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - UMASK_SET=022 #optional
    volumes:
      - ${HTPC_CONFIG_DIR}/sonarr:/config
      - ${HTPC_DATA_DIR}/TV:/tv
      - ${HTPC_WORK_DIR}/downloads:/downloads
      - ${HTPC_WORK_DIR}/incomplete-downloads:/incomplete-downloads
    ports:
      - 8989:8989
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Radarr (https://radarr.video)
  #   Tv Show Media Management
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - UMASK_SET=022 #optional
    volumes:
      - ${HTPC_CONFIG_DIR}/radarr:/config
      - ${HTPC_DATA_DIR}/Movies:/movies
      - ${HTPC_WORK_DIR}/downloads:/downloads
      - ${HTPC_WORK_DIR}/incomplete-downloads:/incomplete-downloads
    ports:
      - 7878:7878
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Readarr (https://github.com/Readarr/Readarr)
  #   EBook Media Management
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/readarr:/config
      - ${HTPC_DATA_DIR}/Books:/books
      - ${HTPC_WORK_DIR}/downloads:/downloads
    ports:
      - 8787:8787
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # SABnzbd ()
  #   Usenet Media Downloader
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/sabnzbd:/config
      - ${HTPC_WORK_DIR}/downloads:/downloads
      - ${HTPC_WORK_DIR}/incomplete-downloads:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Deluge ()
  #   Torrent Media Downloader
  deluge:
    image: binhex/arch-delugevpn:latest
    container_name: deluge
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - VPN_ENABLED=${HTPC_VPN_ENABLED:-yes}
      - VPN_USER=${HTPC_VPN_USER}
      - VPN_PASS=${HTPC_VPN_PASS}
      - VPN_PROV=${HTPC_VPN_PROV:-pia}
      - VPN_CLIENT=${HTPC_VPN_CLIENT:-openvpn}
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=${HTPC_VPN_NETWORK:-192.168.1.0/24}
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=502
      - DEBUG=false
    volumes:
      - ${HTPC_CONFIG_DIR}/deluge:/config
      - ${HTPC_WORK_DIR}/downloads:/downloads
    ports:
      - 8112:8112
      - 8118:8118
      - 6881:6881
      - 6881:6881/udp
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Overseerr ()
  #   Media Request Service
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/overseerr:/config
    ports:
      - 5055:5055
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Requestrr (https://github.com/darkalfx/requestrr)
  #    Discord chat bot for Media Requests
  requestrr:
    image: darkalfx/requestrr:latest
    container_name: requestrr
    volumes:
      - ${HTPC_CONFIG_DIR}/requestrr:/root/config
    ports:
      - 4545:4545
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend

  # Searcharr (https://github.com/toddrob99/searcharr)
  #    Telegram bot for Media Requests
  searcharr:
    image: toddrob/searcharr:latest
    container_name: searcharr
    environment:
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/searcharr/data:/app/data
      - ${HTPC_CONFIG_DIR}/searcharr/logs:/app/logs
      - ${HTPC_CONFIG_DIR}/searcharr/settings.py:/app/settings.py
    restart: always
    networks:
      - htpc-backend

  # Tautulli ()
  #   Plex Media management and monitoring service
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/tautulli:/config
      - ${HTPC_CONFIG_DIR}/config/logs:/plex_logs:ro
    ports:
      - 8181:8181
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend


  #
  # Management Services
  #

  # Watchtower ()
  #    Docker image watcher/updater
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - "WATCHTOWER_SCHEDULE=0 3 * * 6" # At 03:00 on Saturday.
      - WATCHTOWER_CLEANUP=${HTPC_UPDATE_CLEANUP:-true}
    volumes:
      - ${HTPC_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock

  # Portainer
  #    Docker UI management console
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${HTPC_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ${HTPC_CONFIG_DIR}/portainer:/data
    ports:
      - 9000:9000
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  htpc-backend:
    driver: bridge