services:
  # Watchtower (https://containrrr.dev/watchtower/)
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - "WATCHTOWER_SCHEDULE=0 3 * * 6" # At 03:00 on Saturday.
      - WATCHTOWER_CLEANUP=${HTPC_UPDATE_CLEANUP:-true}
    volumes:
      - ${HTPC_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock

  # Portainer (https://www.portainer.io/)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${HTPC_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ${HTPC_CONFIG_DIR}/portainer:/data
    ports:
      - 9000:9000
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  htpc-backend:
    driver: bridge