services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${HTPC_CONFIG_DIR}/nginx/data:/data
      - ${HTPC_CONFIG_DIR}/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend