services:
  # Ubooquity (https://vaemendis.net/ubooquity/)
  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - MAXMEM=2048
    volumes:
      - ${HTPC_CONFIG_DIR}/ubooquity:/config
      - ${HTPC_DATA_DIR}/Books:/books
      - ${HTPC_DATA_DIR}/Comics:/comics
      - ${HTPC_DATA_DIR}:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend