services:
  # Readarr (https://github.com/Readarr/Readarr)
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/readarr:/config
      - ${HTPC_DATA_DIR}/Books:/books
      - ${HTPC_WORK_DIR}/downloads:/downloads
    ports:
      - 8787:8787
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend