services:
  # Radarr (https://radarr.video)
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - UMASK_SET=022 #optional
    volumes:
      - ${HTPC_CONFIG_DIR}/radarr:/config
      - ${HTPC_DATA_DIR}/Movies:/movies
      - ${HTPC_WORK_DIR}/downloads:/downloads
      - ${HTPC_WORK_DIR}/incomplete-downloads:/incomplete-downloads
    ports:
      - 7878:7878
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge