services:
  # Deluge (https://deluge-torrent.org/)
  deluge:
    image: binhex/arch-delugevpn:latest
    container_name: deluge
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - VPN_ENABLED=${HTPC_VPN_ENABLED:-yes}
      - VPN_USER=${HTPC_VPN_USER}
      - VPN_PASS=${HTPC_VPN_PASS}
      - VPN_PROV=${HTPC_VPN_PROV:-pia}
      - VPN_CLIENT=${HTPC_VPN_CLIENT:-openvpn}
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=${HTPC_VPN_NETWORK:-192.168.1.0/24}
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=502
      - DEBUG=false
    volumes:
      - ${HTPC_CONFIG_DIR}/deluge:/config
      - ${HTPC_WORK_DIR}/downloads:/downloads
    ports:
      - 8112:8112
      - 8118:8118
      - 6881:6881
      - 6881:6881/udp
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend