services:
  # Tautulli (https://tautulli.com/)
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/tautulli:/config
      - ${HTPC_CONFIG_DIR}/config/logs:/plex_logs:ro
    ports:
      - 8181:8181
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend