services:
  # SABnzbd (https://sabnzbd.org/)
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/sabnzbd:/config
      - ${HTPC_WORK_DIR}/downloads:/downloads
      - ${HTPC_WORK_DIR}/incomplete-downloads:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend