services:
  # Sonarr (https://sonarr.tv)
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
      - UMASK_SET=022 #optional
    volumes:
      - ${HTPC_CONFIG_DIR}/sonarr:/config
      - ${HTPC_DATA_DIR}/TV:/tv
      - ${HTPC_WORK_DIR}/downloads:/downloads
      - ${HTPC_WORK_DIR}/incomplete-downloads:/incomplete-downloads
    ports:
      - 8989:8989
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge