services:
  # Bazarr (https://www.bazarr.media/)
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/bazarr:/config
      - ${HTPC_DATA_DIR}/Movies:/movies #optional
      - ${HTPC_DATA_DIR}/TV:/tv #optional
    ports:
      - 6767:6767
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend