services:
  # Unmanic (https://github.com/Unmanic/unmanic)
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
    volumes:
      - ${HTPC_CONFIG_DIR}/unmanic:/config
      - ${HTPC_DATA_DIR}:/library
      - ${HTPC_WORK_DIR}/unmanic:/tmp/unmanic
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge