services:
  # EmulatorJS (https://github.com/linuxserver/emulatorjs)
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=${HTPC_PUID:-1000}
      - PGID=${HTPC_PGID:-1000}
      - TZ=${HTPC_TIMEZONE:-America/Chicago}
    volumes:
      - ${HTPC_CONFIG_DIR}/emulatorjs:/config
      - ${HTPC_DATA_DIR}/Roms:/data
    ports:
      - 3000:3000
      - 8088:80
      - 4001:4001 #optional
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - htpc-backend
networks:
  htpc-backend:
    driver: bridge
    external: true
    name: htpc-backend